title: 全能官网

url: http://www.qnnsafe.com

assets:
  dirname: assets
  baseurl: /assets/
  sources:
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
  #compress:
    #css: sass
    #js:  uglifier
  cache_assets: true

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - Rakefile
  - README.md
